// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSids
{
        public const string achievement_view_the_tutorial = "CgkI0sHb4LocEAIQBA"; // <GPGSID>
        public const string achievement_view_your_stats = "CgkI0sHb4LocEAIQAw"; // <GPGSID>
        public const string achievement_won_a_game = "CgkI0sHb4LocEAIQBQ"; // <GPGSID>
        public const string achievement_won_10_games = "CgkI0sHb4LocEAIQBg"; // <GPGSID>
        public const string achievement_start_a_game = "CgkI0sHb4LocEAIQAg"; // <GPGSID>
        public const string leaderboard_tap_down_leaderboard = "CgkI0sHb4LocEAIQBw"; // <GPGSID>

}

